import asyncio
import uuid
from uuid import uuid4
from datetime import datetime
from pprint import pprint

from ports.repository import RepositoryPort
from adapters.postgres_repository import PostgresRepository
from adapters.mock_ai_provider import MockAIProvider
from domain.engine import CognitiveEngine
from domain.models import Fragment, Space, Product, ProductSection, StyleFamily, Archetype, InterventionLevel
from domain.services.blueprinter import Blueprinter
from domain.services.drafter import Drafter
from domain.services.formatter import Formatter
from infrastructure.database import SessionLocal

async def main():
    print("=== FINAL SYSTEM SMOKE TEST ===")
    
    # 1. Setup Dependencies
    db = SessionLocal()
    repo = PostgresRepository(db)
    ai_provider = MockAIProvider()
    engine = CognitiveEngine(ai_provider)
    blueprinter = Blueprinter(repo, ai_provider)
    drafter = Drafter(repo, ai_provider)
    
    # 2. Setup Data: Create a dedicated Space
    print("\n[TEST] Creating Space...")
    space = repo.create_space(name=f"Audit Space {datetime.now().isoformat()}", description="Testing Area")
    space_id = space.id # Use the ID generated by the repo/DB
    print(f"[OK] Created Space: {space.name} ({space.id})")
    
    # 3. Ingest Fragments (Simulating Knowledge Base)
    fragments = [
        Fragment(id=uuid4(), space_id=space_id, raw_text="Quantum physics describes nature at the smallest scales."),
        Fragment(id=uuid4(), space_id=space_id, raw_text="Entanglement allows particles to affect each other instantly."),
        Fragment(id=uuid4(), space_id=space_id, raw_text="Schrödinger's cat illustrates the paradox of superposition.")
    ]
    for f in fragments:
        await repo.save_fragment(f)
    print(f"[OK] Ingested {len(fragments)} Fragments into Space.")
    
    # 4. Create an Idea (Simulating Genesis)
    idea_id = uuid4()
    # Manually creating idea to skip complex genesis flow for this smoke test, focusing on Editorial
    from domain.models import Idea
    idea = Idea(
        id=idea_id, 
        space_id=space_id, 
        title_provisional="The Quantum Paradox", 
        status="consolidated"
    )
    await repo.save_idea(idea)
    print(f"[OK] Created Idea: {idea.title_provisional}")
    
    # 5. Create Product (The Publisher)
    product_id = uuid4()
    product = Product(
        id=product_id,
        space_id=space_id,
        idea_id=idea_id,
        title="Understanding Quantum Mechanics",
        archetype=Archetype.NON_FICTION,
        style_family=StyleFamily.CLASSIC_PUBLISHER,
        status="draft"
    )
    repo.create_product(product)
    print(f"[OK] Created Product: {product.title}")
    
    # 6. Generate Blueprint (Blueprinter)
    print("\n[TEST] Generating Blueprint...")
    sections = await blueprinter.generate_structure(product_id)
    if sections and len(sections) > 0:
        print(f"[OK] Blueprinter generated {len(sections)} sections.")
        print(f"   - First Section: {sections[0].title}")
    else:
        print("[FAIL] Blueprinter returned no sections.")
        return

    # 7. Draft Content (Drafter)
    target_section = sections[0]
    print(f"\n[TEST] Drafting content for section: {target_section.title}")
    # Simulate DB state refetch
    updated_product = repo.get_product(product_id)
    target_section = updated_product.sections[0] # Ensure we have the persisted one
    
    await drafter.draft_section(updated_product, target_section, InterventionLevel.FLOW)
    
    # Verify content
    final_product = repo.get_product(product_id)
    drafted_section = final_product.sections[0]
    if drafted_section.content and len(drafted_section.content) > 50:
         print(f"[OK] Content drafted: {drafted_section.content[:70]}...")
    else:
         print("[FAIL] Content draft missing or too short.")
         
    # 8. Export (Formatter)
    print("\n[TEST] Exporting Product (HTML & Markdown)...")
    html_out = Formatter.render_html(final_product)
    md_out = Formatter.render_markdown(final_product)
    
    if "<html>" in html_out and final_product.title in html_out:
        print(f"[OK] HTML Export verification passed ({len(html_out)} chars).")
    else:
         print("[FAIL] HTML Export malformed.")

    if "# " in md_out and final_product.title in md_out:
        print(f"[OK] Markdown Export verification passed ({len(md_out)} chars).")
    else:
         print("[FAIL] Markdown Export malformed.")
         
    print("\n=== SMOKE TEST COMPLETE: SUCCESS ===")

if __name__ == "__main__":
    asyncio.run(main())
