
import requests
import sys

BASE_URL = "http://localhost:8000"

def log(msg):
    print(f"[SIMULATION] {msg}")

def check(name, resp, expected=[200, 201]):
    if resp.status_code in expected:
        log(f"[PASS] {name}")
        try:
            return resp.json()
        except:
            return resp.text
    else:
        log(f"[FAIL] {name}: {resp.status_code} {resp.text}")
        sys.exit(1)

try:
    log("Starting Full Flow Simulation")

    # 1. Create Space
    log("Phase 1: Auth & Onboarding (Creating Space)")
    space_res = check("Create Space", requests.post(f"{BASE_URL}/spaces/", json={
        "name": "Simulated Space",
        "description": "Auto-generated by simulation script"
    }))
    space_id = space_res['id']
    log(f"Created Space ID: {space_id}")

    # 2. Create Product
    log("Phase 2: Product & Ideation (Creating Product)")
    product_res = check("Create Product", requests.post(f"{BASE_URL}/products/", json={
        "title": "Simulation Product Book",
        "archetype": "non_fiction",
        "space_id": space_id
    }))
    product_id = product_res['id']
    log(f"Created Product ID: {product_id}")

    # 3. Ingest Ideas
    log("Phase 2b: Ingesting Ideas")
    ingest_res = check("Ingest Fragment", requests.post(f"{BASE_URL}/ingest/", json={
        "text": "The core concept of this book is to test the system integrity.",
        "source": "simulation_script",
        "space_id": space_id
    }))
    log(f"Ingestion Decision: {ingest_res.get('decision', 'unknown')}")

    # 4. Export
    log("Phase 4: Export & Persistence")
    export_url = f"{BASE_URL}/products/{product_id}/export?format=html"
    export_res = requests.get(export_url)
    if export_res.status_code == 200:
        log("[PASS] Export HTML")
        if "Simulation Product Book" in export_res.text:
            log("[PASS] Export Content Verified (Title found)")
        else:
            log("[WARNING] Export Content missing title (Blueprint might be empty)")
    else:
        log(f"[FAIL] Export HTML: {export_res.status_code}")
        sys.exit(1)

    log("ALL PHASES PASSED SUCCESSFULLY.")

except Exception as e:
    log(f"[CRITICAL ERROR] {e}")
    sys.exit(1)
